[package]
name = "midnight_girls"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version="4", default-features = false, features = ["macros"] }
actix-files = "0"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
upon = { version = "0", default-features = false, features = ["serde"] }

[profile.release]
strip = "symbols"
lto = "fat"
